#Updated via Settings Menu
#Thu Apr 09 17:24:04 EEST 2026
break_time=10
color_bg=\#FFE6EEEA
color_break=\#718249FF
color_focus=\#B14565FF
color_username=\#FF99CCFF
current_hair=girl-hair-brunette.png
current_outfit=girl-outfit-protagonist.png
current_skin=girl-skintone-medium.png
focus_time=20
twitch_channel=scoobxie
